export const BackendAPIActionTypes = {
  FETCH_BACKEND_API_START: 'FETCH_BACKEND_API_START',
  FETCH_BACKEND_API_SUCCESS: 'FETCH_BACKEND_API_SUCCESS',
  FETCH_BACKEND_API_FAILURE: 'FETCH_BACKEND_API_FAILURE',
  POST_BACKEND_API_START: 'POST_BACKEND_API_START',
  POST_BACKEND_API_SUCCESS: 'POST_BACKEND_API_SUCCESS',
  POST_BACKEND_API_FAILURE: 'POST_BACKEND_API_FAILURE'
};
