export const BackendAPIActionTypes = {
  FETCH_BACKEND_API_START: 'FETCH_BACKEND_API_START',
  FETCH_BACKEND_API_SUCCESS: 'FETCH_BACKEND_API_SUCCESS',
  FETCH_BACKEND_API_FAILURE: 'FETCH_BACKEND_API_FAILURE',
};
