export const TestCollection1ActionTypes = {
  FETCH_PRODUCTS_START: 'FETCH_TESTCOLLECTION1_START',
  FETCH_PRODUCTS_SUCCESS: 'FETCH_TESTCOLLECTION1SUCCESS',
  FETCH_PRODUCTS_FAILURE: 'FETCH_TESTCOLLECTION1_FAILURE',
};
